### ISSUE TITLE
Add meta descriptions to pages & check it is applied on first serve

### ISSUE THREAD

**Issue by AspireOne** [AspireOne/Companion#40]
**Description**
Pages must have meta description for SEO. To each page (at least public ones - the ones that are not indexed in robots.txt are secondary), add a description. This is part of a larger task to define our marketing materials.

**Requirements**
- [ ] All public & combined pages must have quality meta description both according to best practices, and to get the best marketing
- [ ] It should be added through the specific <PublicPage>, <CombinedPage> etc. component
- [ ] You must also check if it is applied on the first HTML serve, before the page is loaded - if not, fix it. (It SHOULD be though - it should normally be pre-rendered using SSG)
- [ ] Make sure to also alter the universal meta description at PageHead.tsx
